[project]
name = "adt"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tasks]

[dependencies]
rust = ">=1.83.0,<1.84"
